Commit

diff --git a/TheFinalCut/jenkinsfile b/TheFinalCut/jenkinsfile
--- a/TheFinalCut/jenkinsfile
+++ b/TheFinalCut/jenkinsfile
@@ -1,23 +1,26 @@
 pipeline {
     agent any
-    
     options {
         timestamps()
     }
 
-    tools {
-        go 'Go 1.16'
-    }
-    
     stages {
-        stage ("Download source from git"){
-            steps{
-                git 'https://github.com/Fenikks/word-cloud-generator.git'
+        stage ('Test') {
+            agent {
+                dockerfile { 
+                    filename 'Dockerfile.GoLang' 
+                    args '--network host'
+               }
             }
-        }
-        stage ("Build"){
-            steps{
-                sh '''export GOPATH=$WORKSPACE/go
+            steps {
+                sh '''
+                make lint && make test
+                 if [ $? -ne 0 ];
+                    then
+                        echo "Test error"
+                        exit 1
+                    fi
+                export GOPATH=$WORKSPACE/go
                 export PATH="$PATH:$(go env GOPATH)/bin"               
                 go get github.com/tools/godep
                 go get github.com/smartystreets/goconvey
@@ -28,43 +31,62 @@ pipeline {
                 GOOS=linux GOARCH=amd64 go build -o ./artifacts/word-cloud-generator -v 
                 md5sum artifacts/word-cloud-generator
                 ls -l artifacts/
-                gzip -f ./artifacts/word-cloud-generator'''
+                gzip -f ./artifacts/word-cloud-generator
+                cat static/version
+                '''
+                nexusArtifactUploader 
+                  artifacts: [[
+                    artifactId: 'word-cloud-generator', 
+                    classifier: '', file: 'artifacts/word-cloud-generator.gz', 
+                    type: 'gz']], 
+                  credentialsId: 'uploader', 
+                  groupId: "$git_branch", 
+                  nexusUrl: 'localhost:8081', 
+                  nexusVersion: 'nexus3', 
+                  protocol: 'http', 
+                  repository: 'word-cloud-build', 
+                  version: '1.$BUILD_NUMBER'
             }
         }
-        stage ("Upload to nexus") {
-            steps {
-                nexusArtifactUploader (
-                    artifacts: [[
-                        artifactId: 'word-cloud-generator', 
-                        classifier: '', 
-                        file: 'artifacts/word-cloud-generator.gz', 
-                        type: 'gz']], 
-                    credentialsId: 'uploader', 
-                    groupId: "${GIT_BRANCH}", 
-                    nexusUrl: '192.168.50.20:8081', 
-                    nexusVersion: 'nexus3', 
-                    protocol: 'http', 
-                    repository: 'word-cloud-build', 
-                    version: '1.$BUILD_NUMBER'
-                )
+        stage('Testing') {
+            agent {
+                dockerfile { 
+                    filename 'Dockerfile.Alpine' 
+                    args '--network host'
+               }
             }
-        }   
-        stage ("Test and install on stading") {
             steps {
-                sh '''
-                sshpass -p 'vagrant' ssh vagrant@192.168.50.40 -o StrictHostKeyChecking=no "cd /opt/wordcloud/
-                sudo curl -u downloader:downloader -X GET "http://192.168.50.20:8081/repository/word-cloud-build/${GIT_BRANCH}/word-cloud-generator/1.$BUILD_NUMBER/word-cloud-generator-1.$BUILD_NUMBER.gz" -o /opt/wordcloud/word-cloud-generator.gz
-                if [[ $? -ne 0 ]];
-                  then
-                    echo "File not found"
-                    exit 1
-                  else
-                    sudo service wordcloud stop
-                    sudo gunzip -f /opt/wordcloud/word-cloud-generator.gz
-                    sudo chmod +x /opt/wordcloud/word-cloud-generator
-                    sudo service wordcloud start
-                fi"
-                '''
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'downloader', 
+                        usernameVariable: 'nexus_user', 
+                        passwordVariable: 'nexus_password'
+                    )])
+                {
+                  sh '''
+                   curl -u ${nexus_user}:${nexus_password} -X GET "http://localhost:8081/repository/word-cloud-build/$git_branch/word-cloud-generator/1.$BUILD_NUMBER/word-cloud-generator-1.$BUILD_NUMBER.gz" -o /opt/wordcloud/word-cloud-generator.gz
+                   if [[ $? -ne 0 ]];
+                   then
+                       echo "File not found"
+                       exit 1
+                   else
+                       gunzip -f /opt/wordcloud/word-cloud-generator.gz
+                       chmod +x /opt/wordcloud/word-cloud-generator
+                       /opt/wordcloud/word-cloud-generator &
+                       sleep 5
+                       res=`curl -s -H "Content-Type: application/json" -d '{"text":"ths is a really really really important thing this is"}' http://localhost:8888/version | jq '. | length'`
+                       if [[ "1" != "$res" ]]; then 
+                          exit 98
+                       fi
+                       res=`curl -s -H "Content-Type: application/json" -d '{"text":"ths is a really really really important thing this is"}' http://localhost:8888/api | jq '. | length'`
+                       if [[ "7" != "$res" ]]; then
+                          exit 99
+                       fi
+                       sleep 90
+                   fi
+                   
+                  '''
+                }
             }
         }
     }
